<?php
/**
 * File: config/creature.php
 * Purpose: Provides functionality for the config module.
 */

return [
    'groups' => [
        'base' => [
            'label' => 'lang:app.creature.config.groups.base.label',
            'fields' => [
                ['name' => 'name', 'label' => 'lang:app.creature.config.groups.base.fields.name.label', 'type' => 'text'],
                ['name' => 'subname', 'label' => 'lang:app.creature.config.groups.base.fields.subname.label', 'type' => 'text'],
                ['name' => 'minlevel', 'label' => 'lang:app.creature.config.groups.base.fields.minlevel.label', 'type' => 'number'],
                ['name' => 'maxlevel', 'label' => 'lang:app.creature.config.groups.base.fields.maxlevel.label', 'type' => 'number'],
                ['name' => 'exp', 'label' => 'lang:app.creature.config.groups.base.fields.exp.label', 'type' => 'number', 'help' => 'lang:app.creature.config.groups.base.fields.exp.help'],
                ['name' => 'faction', 'label' => 'lang:app.creature.config.groups.base.fields.faction.label', 'type' => 'number'],
                ['name' => 'scale', 'label' => 'lang:app.creature.config.groups.base.fields.scale.label', 'type' => 'number'],
                ['name' => 'speed_walk', 'label' => 'lang:app.creature.config.groups.base.fields.speed_walk.label', 'type' => 'number'],
                ['name' => 'speed_run', 'label' => 'lang:app.creature.config.groups.base.fields.speed_run.label', 'type' => 'number'],
                ['name' => 'rank', 'label' => 'lang:app.creature.config.groups.base.fields.rank.label', 'type' => 'number'],
                ['name' => 'type', 'label' => 'lang:app.creature.config.groups.base.fields.type.label', 'type' => 'number'],
            ],
        ],
        'combat' => [
            'label' => 'lang:app.creature.config.groups.combat.label',
            'fields' => [
                ['name' => 'dmgschool', 'label' => 'lang:app.creature.config.groups.combat.fields.dmgschool.label', 'type' => 'number'],
                ['name' => 'baseattacktime', 'label' => 'lang:app.creature.config.groups.combat.fields.baseattacktime.label', 'type' => 'number'],
                ['name' => 'rangeattacktime', 'label' => 'lang:app.creature.config.groups.combat.fields.rangeattacktime.label', 'type' => 'number'],
                ['name' => 'mindmg', 'label' => 'lang:app.creature.config.groups.combat.fields.mindmg.label', 'type' => 'number'],
                ['name' => 'maxdmg', 'label' => 'lang:app.creature.config.groups.combat.fields.maxdmg.label', 'type' => 'number'],
                ['name' => 'dmg_multiplier', 'label' => 'lang:app.creature.config.groups.combat.fields.dmg_multiplier.label', 'type' => 'number'],
                ['name' => 'basevariance', 'label' => 'lang:app.creature.config.groups.combat.fields.basevariance.label', 'type' => 'number'],
                ['name' => 'rangevariance', 'label' => 'lang:app.creature.config.groups.combat.fields.rangevariance.label', 'type' => 'number'],
                ['name' => 'attackpower', 'label' => 'lang:app.creature.config.groups.combat.fields.attackpower.label', 'type' => 'number'],
                ['name' => 'rangedattackpower', 'label' => 'lang:app.creature.config.groups.combat.fields.rangedattackpower.label', 'type' => 'number'],
            ],
        ],
        'vitals' => [
            'label' => 'lang:app.creature.config.groups.vitals.label',
            'fields' => [
                ['name' => 'healthmodifier', 'label' => 'lang:app.creature.config.groups.vitals.fields.healthmodifier.label', 'type' => 'number'],
                ['name' => 'manamodifier', 'label' => 'lang:app.creature.config.groups.vitals.fields.manamodifier.label', 'type' => 'number'],
                ['name' => 'armormodifier', 'label' => 'lang:app.creature.config.groups.vitals.fields.armormodifier.label', 'type' => 'number'],
                ['name' => 'resistance1', 'label' => 'lang:app.creature.config.groups.vitals.fields.resistance1.label', 'type' => 'number'],
                ['name' => 'resistance2', 'label' => 'lang:app.creature.config.groups.vitals.fields.resistance2.label', 'type' => 'number'],
                ['name' => 'resistance3', 'label' => 'lang:app.creature.config.groups.vitals.fields.resistance3.label', 'type' => 'number'],
                ['name' => 'resistance4', 'label' => 'lang:app.creature.config.groups.vitals.fields.resistance4.label', 'type' => 'number'],
                ['name' => 'resistance5', 'label' => 'lang:app.creature.config.groups.vitals.fields.resistance5.label', 'type' => 'number'],
                ['name' => 'resistance6', 'label' => 'lang:app.creature.config.groups.vitals.fields.resistance6.label', 'type' => 'number'],
            ],
        ],
        'drops' => [
            'label' => 'lang:app.creature.config.groups.drops.label',
            'fields' => [
                ['name' => 'lootid', 'label' => 'lang:app.creature.config.groups.drops.fields.lootid.label', 'type' => 'number'],
                ['name' => 'pickpocketloot', 'label' => 'lang:app.creature.config.groups.drops.fields.pickpocketloot.label', 'type' => 'number'],
                ['name' => 'skinloot', 'label' => 'lang:app.creature.config.groups.drops.fields.skinloot.label', 'type' => 'number'],
                ['name' => 'mingold', 'label' => 'lang:app.creature.config.groups.drops.fields.mingold.label', 'type' => 'number'],
                ['name' => 'maxgold', 'label' => 'lang:app.creature.config.groups.drops.fields.maxgold.label', 'type' => 'number'],
            ],
        ],
        'ai' => [
            'label' => 'lang:app.creature.config.groups.ai.label',
            'fields' => [
                ['name' => 'ainame', 'label' => 'lang:app.creature.config.groups.ai.fields.ainame.label', 'type' => 'text'],
                ['name' => 'scriptname', 'label' => 'lang:app.creature.config.groups.ai.fields.scriptname.label', 'type' => 'text'],
                ['name' => 'gossip_menu_id', 'label' => 'lang:app.creature.config.groups.ai.fields.gossip_menu_id.label', 'type' => 'number'],
                ['name' => 'movementtype', 'label' => 'lang:app.creature.config.groups.ai.fields.movementtype.label', 'type' => 'number'],
            ],
        ],
        'flags' => [
            'label' => 'lang:app.creature.config.groups.flags.label',
            'fields' => [
                ['name' => 'npcflag', 'label' => 'lang:app.creature.config.groups.flags.fields.npcflag.label', 'type' => 'number', 'bitmask' => true],
                ['name' => 'unit_flags', 'label' => 'lang:app.creature.config.groups.flags.fields.unit_flags.label', 'type' => 'number', 'bitmask' => true],
                ['name' => 'unit_flags2', 'label' => 'lang:app.creature.config.groups.flags.fields.unit_flags2.label', 'type' => 'number', 'bitmask' => true],
                ['name' => 'type_flags', 'label' => 'lang:app.creature.config.groups.flags.fields.type_flags.label', 'type' => 'number', 'bitmask' => true],
                ['name' => 'flags_extra', 'label' => 'lang:app.creature.config.groups.flags.fields.flags_extra.label', 'type' => 'number', 'bitmask' => true],
                ['name' => 'dynamicflags', 'label' => 'lang:app.creature.config.groups.flags.fields.dynamicflags.label', 'type' => 'number', 'bitmask' => true],
            ],
        ],
    ],
    'flags' => [
        'npcflag' => [
            0 => 'lang:app.creature.config.flags.npcflag.0',
            1 => 'lang:app.creature.config.flags.npcflag.1',
            2 => 'lang:app.creature.config.flags.npcflag.2',
            3 => 'lang:app.creature.config.flags.npcflag.3',
            4 => 'lang:app.creature.config.flags.npcflag.4',
            5 => 'lang:app.creature.config.flags.npcflag.5',
            6 => 'lang:app.creature.config.flags.npcflag.6',
            7 => 'lang:app.creature.config.flags.npcflag.7',
            8 => 'lang:app.creature.config.flags.npcflag.8',
            9 => 'lang:app.creature.config.flags.npcflag.9',
            10 => 'lang:app.creature.config.flags.npcflag.10',
            11 => 'lang:app.creature.config.flags.npcflag.11',
            12 => 'lang:app.creature.config.flags.npcflag.12',
            13 => 'lang:app.creature.config.flags.npcflag.13',
            14 => 'lang:app.creature.config.flags.npcflag.14',
            15 => 'lang:app.creature.config.flags.npcflag.15',
            16 => 'lang:app.creature.config.flags.npcflag.16',
            17 => 'lang:app.creature.config.flags.npcflag.17',
            18 => 'lang:app.creature.config.flags.npcflag.18',
            19 => 'lang:app.creature.config.flags.npcflag.19',
            20 => 'lang:app.creature.config.flags.npcflag.20',
            21 => 'lang:app.creature.config.flags.npcflag.21',
            22 => 'lang:app.creature.config.flags.npcflag.22',
            23 => 'lang:app.creature.config.flags.npcflag.23',
        ],
        'unit_flags' => [
            0 => 'lang:app.creature.config.flags.unit_flags.0',
            1 => 'lang:app.creature.config.flags.unit_flags.1',
            2 => 'lang:app.creature.config.flags.unit_flags.2',
            3 => 'lang:app.creature.config.flags.unit_flags.3',
            4 => 'lang:app.creature.config.flags.unit_flags.4',
            5 => 'lang:app.creature.config.flags.unit_flags.5',
            6 => 'lang:app.creature.config.flags.unit_flags.6',
            7 => 'lang:app.creature.config.flags.unit_flags.7',
            8 => 'lang:app.creature.config.flags.unit_flags.8',
            9 => 'lang:app.creature.config.flags.unit_flags.9',
            10 => 'lang:app.creature.config.flags.unit_flags.10',
            11 => 'lang:app.creature.config.flags.unit_flags.11',
            12 => 'lang:app.creature.config.flags.unit_flags.12',
            13 => 'lang:app.creature.config.flags.unit_flags.13',
            14 => 'lang:app.creature.config.flags.unit_flags.14',
            15 => 'lang:app.creature.config.flags.unit_flags.15',
            16 => 'lang:app.creature.config.flags.unit_flags.16',
            17 => 'lang:app.creature.config.flags.unit_flags.17',
            18 => 'lang:app.creature.config.flags.unit_flags.18',
            19 => 'lang:app.creature.config.flags.unit_flags.19',
            20 => 'lang:app.creature.config.flags.unit_flags.20',
            21 => 'lang:app.creature.config.flags.unit_flags.21',
        ],
        'unit_flags2' => [
            0 => 'lang:app.creature.config.flags.unit_flags2.0',
            1 => 'lang:app.creature.config.flags.unit_flags2.1',
            2 => 'lang:app.creature.config.flags.unit_flags2.2',
            3 => 'lang:app.creature.config.flags.unit_flags2.3',
            4 => 'lang:app.creature.config.flags.unit_flags2.4',
            5 => 'lang:app.creature.config.flags.unit_flags2.5',
            6 => 'lang:app.creature.config.flags.unit_flags2.6',
            7 => 'lang:app.creature.config.flags.unit_flags2.7',
            8 => 'lang:app.creature.config.flags.unit_flags2.8',
            9 => 'lang:app.creature.config.flags.unit_flags2.9',
        ],
        'type_flags' => [
            0 => 'lang:app.creature.config.flags.type_flags.0',
            1 => 'lang:app.creature.config.flags.type_flags.1',
            2 => 'lang:app.creature.config.flags.type_flags.2',
            3 => 'lang:app.creature.config.flags.type_flags.3',
            4 => 'lang:app.creature.config.flags.type_flags.4',
            5 => 'lang:app.creature.config.flags.type_flags.5',
            6 => 'lang:app.creature.config.flags.type_flags.6',
            7 => 'lang:app.creature.config.flags.type_flags.7',
        ],
        'flags_extra' => [
            0 => 'lang:app.creature.config.flags.flags_extra.0',
            1 => 'lang:app.creature.config.flags.flags_extra.1',
            2 => 'lang:app.creature.config.flags.flags_extra.2',
            3 => 'lang:app.creature.config.flags.flags_extra.3',
            4 => 'lang:app.creature.config.flags.flags_extra.4',
            5 => 'lang:app.creature.config.flags.flags_extra.5',
            6 => 'lang:app.creature.config.flags.flags_extra.6',
        ],
        'dynamicflags' => [
            0 => 'lang:app.creature.config.flags.dynamicflags.0',
            1 => 'lang:app.creature.config.flags.dynamicflags.1',
            2 => 'lang:app.creature.config.flags.dynamicflags.2',
            3 => 'lang:app.creature.config.flags.dynamicflags.3',
            4 => 'lang:app.creature.config.flags.dynamicflags.4',
            5 => 'lang:app.creature.config.flags.dynamicflags.5',
        ],
    ],
    'factions' => [
        14 => 'lang:app.creature.config.factions.14',
        35 => 'lang:app.creature.config.factions.35',
        68 => 'lang:app.creature.config.factions.68',
        69 => 'lang:app.creature.config.factions.69',
        70 => 'lang:app.creature.config.factions.70',
        74 => 'lang:app.creature.config.factions.74',
        84 => 'lang:app.creature.config.factions.84',
        120 => 'lang:app.creature.config.factions.120',
        121 => 'lang:app.creature.config.factions.121',
        122 => 'lang:app.creature.config.factions.122',
        123 => 'lang:app.creature.config.factions.123',
        124 => 'lang:app.creature.config.factions.124',
        169 => 'lang:app.creature.config.factions.169',
        469 => 'lang:app.creature.config.factions.469',
        529 => 'lang:app.creature.config.factions.529',
        530 => 'lang:app.creature.config.factions.530',
        609 => 'lang:app.creature.config.factions.609',
        910 => 'lang:app.creature.config.factions.910',
        934 => 'lang:app.creature.config.factions.934',
        935 => 'lang:app.creature.config.factions.935',
    ],
];

