<?php
/**
 * File: config/quest.php
 * Purpose: Provides functionality for the config module.
 */

return [
    'fields' => [
        'enums' => [
            'quest_type' => [
                0 => 'lang:app.quest.config.fields.enums.quest_type.0',
                1 => 'lang:app.quest.config.fields.enums.quest_type.1',
                2 => 'lang:app.quest.config.fields.enums.quest_type.2',
                3 => 'lang:app.quest.config.fields.enums.quest_type.3',
                4 => 'lang:app.quest.config.fields.enums.quest_type.4',
                5 => 'lang:app.quest.config.fields.enums.quest_type.5',
                6 => 'lang:app.quest.config.fields.enums.quest_type.6',
                7 => 'lang:app.quest.config.fields.enums.quest_type.7',
            ],
        ],
        'bitmasks' => [
            'races' => [
                0 => 'lang:app.quest.config.fields.bitmasks.races.0',
                1 => 'lang:app.quest.config.fields.bitmasks.races.1',
                2 => 'lang:app.quest.config.fields.bitmasks.races.2',
                3 => 'lang:app.quest.config.fields.bitmasks.races.3',
                4 => 'lang:app.quest.config.fields.bitmasks.races.4',
                5 => 'lang:app.quest.config.fields.bitmasks.races.5',
                6 => 'lang:app.quest.config.fields.bitmasks.races.6',
                7 => 'lang:app.quest.config.fields.bitmasks.races.7',
                8 => 'lang:app.quest.config.fields.bitmasks.races.8',
            ],
            'classes' => [
                0 => 'lang:app.quest.config.fields.bitmasks.classes.0',
                1 => 'lang:app.quest.config.fields.bitmasks.classes.1',
                2 => 'lang:app.quest.config.fields.bitmasks.classes.2',
                3 => 'lang:app.quest.config.fields.bitmasks.classes.3',
                4 => 'lang:app.quest.config.fields.bitmasks.classes.4',
                5 => 'lang:app.quest.config.fields.bitmasks.classes.5',
                6 => 'lang:app.quest.config.fields.bitmasks.classes.6',
                7 => 'lang:app.quest.config.fields.bitmasks.classes.7',
                8 => 'lang:app.quest.config.fields.bitmasks.classes.8',
                9 => 'lang:app.quest.config.fields.bitmasks.classes.9',
            ],
            'quest_flags' => [
                0 => 'lang:app.quest.config.fields.bitmasks.quest_flags.0',
                1 => 'lang:app.quest.config.fields.bitmasks.quest_flags.1',
                2 => 'lang:app.quest.config.fields.bitmasks.quest_flags.2',
                3 => 'lang:app.quest.config.fields.bitmasks.quest_flags.3',
                4 => 'lang:app.quest.config.fields.bitmasks.quest_flags.4',
                5 => 'lang:app.quest.config.fields.bitmasks.quest_flags.5',
                6 => 'lang:app.quest.config.fields.bitmasks.quest_flags.6',
                7 => 'lang:app.quest.config.fields.bitmasks.quest_flags.7',
                8 => 'lang:app.quest.config.fields.bitmasks.quest_flags.8',
                9 => 'lang:app.quest.config.fields.bitmasks.quest_flags.9',
                10 => 'lang:app.quest.config.fields.bitmasks.quest_flags.10',
                11 => 'lang:app.quest.config.fields.bitmasks.quest_flags.11',
                12 => 'lang:app.quest.config.fields.bitmasks.quest_flags.12',
                13 => 'lang:app.quest.config.fields.bitmasks.quest_flags.13',
                14 => 'lang:app.quest.config.fields.bitmasks.quest_flags.14',
                15 => 'lang:app.quest.config.fields.bitmasks.quest_flags.15',
                16 => 'lang:app.quest.config.fields.bitmasks.quest_flags.16',
                17 => 'lang:app.quest.config.fields.bitmasks.quest_flags.17',
                18 => 'lang:app.quest.config.fields.bitmasks.quest_flags.18',
                19 => 'lang:app.quest.config.fields.bitmasks.quest_flags.19',
                20 => 'lang:app.quest.config.fields.bitmasks.quest_flags.20',
                21 => 'lang:app.quest.config.fields.bitmasks.quest_flags.21',
                22 => 'lang:app.quest.config.fields.bitmasks.quest_flags.22',
                23 => 'lang:app.quest.config.fields.bitmasks.quest_flags.23',
                24 => 'lang:app.quest.config.fields.bitmasks.quest_flags.24',
                25 => 'lang:app.quest.config.fields.bitmasks.quest_flags.25',
                26 => 'lang:app.quest.config.fields.bitmasks.quest_flags.26',
                27 => 'lang:app.quest.config.fields.bitmasks.quest_flags.27',
                28 => 'lang:app.quest.config.fields.bitmasks.quest_flags.28',
                29 => 'lang:app.quest.config.fields.bitmasks.quest_flags.29',
                30 => 'lang:app.quest.config.fields.bitmasks.quest_flags.30',
                31 => 'lang:app.quest.config.fields.bitmasks.quest_flags.31',
            ],
            'quest_special_flags' => [
                0 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.0',
                1 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.1',
                2 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.2',
                3 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.3',
                4 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.4',
                5 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.5',
                6 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.6',
                7 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.7',
                8 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.8',
                9 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.9',
                10 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.10',
                11 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.11',
                12 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.12',
                13 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.13',
                14 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.14',
                15 => 'lang:app.quest.config.fields.bitmasks.quest_special_flags.15',
            ],
        ],
        'groups' => [
            'basic' => [
                'label' => 'lang:app.quest.config.fields.groups.basic.label',
                'fields' => ['LogTitle', 'QuestDescription', 'QuestLevel', 'MinLevel', 'QuestType'],
            ],
            'objectives' => [
                'label' => 'lang:app.quest.config.fields.groups.objectives.label',
                'fields' => ['ObjectiveText1', 'ObjectiveText2', 'ObjectiveText3', 'ObjectiveText4'],
            ],
            'requirements' => [
                'label' => 'lang:app.quest.config.fields.groups.requirements.label',
                'fields' => ['AllowableRaces', 'RequiredClasses', 'TimeAllowed'],
            ],
            'flags' => [
                'label' => 'lang:app.quest.config.fields.groups.flags.label',
                'fields' => ['Flags', 'SpecialFlags'],
            ],
            'rewards' => [
                'label' => 'lang:app.quest.config.fields.groups.rewards.label',
                'fields' => [
                    'RewardMoney',
                    'RewardSpell',
                    'RewardItem1',
                    'RewardAmount1',
                    'RewardItem2',
                    'RewardAmount2',
                    'RewardItem3',
                    'RewardAmount3',
                    'RewardItem4',
                    'RewardAmount4',
                ],
            ],
            'internal' => [
                'label' => 'lang:app.quest.config.fields.groups.internal.label',
                'fields' => ['SrcSpell', 'StartItem', 'RewardMailTemplateId'],
            ],
        ],
        'fields' => [
            'LogTitle' => ['label' => 'lang:app.quest.config.fields.form.LogTitle.label', 'type' => 'string', 'maxlength' => 255, 'required' => true],
            'QuestDescription' => ['label' => 'lang:app.quest.config.fields.form.QuestDescription.label', 'type' => 'text', 'rows' => 5],
            'QuestLevel' => ['label' => 'lang:app.quest.config.fields.form.QuestLevel.label', 'type' => 'int', 'min' => 1, 'max' => 80, 'default' => 1],
            'MinLevel' => ['label' => 'lang:app.quest.config.fields.form.MinLevel.label', 'type' => 'int', 'min' => 1, 'max' => 80, 'default' => 1],
            'QuestType' => ['label' => 'lang:app.quest.config.fields.form.QuestType.label', 'type' => 'enum', 'enum' => 'quest_type', 'default' => 0],
            'ObjectiveText1' => ['label' => 'lang:app.quest.config.fields.form.ObjectiveText1.label', 'type' => 'string', 'maxlength' => 255],
            'ObjectiveText2' => ['label' => 'lang:app.quest.config.fields.form.ObjectiveText2.label', 'type' => 'string', 'maxlength' => 255],
            'ObjectiveText3' => ['label' => 'lang:app.quest.config.fields.form.ObjectiveText3.label', 'type' => 'string', 'maxlength' => 255],
            'ObjectiveText4' => ['label' => 'lang:app.quest.config.fields.form.ObjectiveText4.label', 'type' => 'string', 'maxlength' => 255],
            'AllowableRaces' => ['label' => 'lang:app.quest.config.fields.form.AllowableRaces.label', 'type' => 'bitmask', 'mask' => 'races', 'default' => 0],
            'RequiredClasses' => ['label' => 'lang:app.quest.config.fields.form.RequiredClasses.label', 'type' => 'bitmask', 'mask' => 'classes', 'default' => 0],
            'TimeAllowed' => ['label' => 'lang:app.quest.config.fields.form.TimeAllowed.label', 'type' => 'int', 'min' => 0, 'help' => 'lang:app.quest.config.fields.form.TimeAllowed.help'],
            'Flags' => ['label' => 'lang:app.quest.config.fields.form.Flags.label', 'type' => 'bitmask', 'mask' => 'quest_flags', 'default' => 0],
            'SpecialFlags' => ['label' => 'lang:app.quest.config.fields.form.SpecialFlags.label', 'type' => 'bitmask', 'mask' => 'quest_special_flags', 'default' => 0, 'help' => 'lang:app.quest.config.fields.form.SpecialFlags.help'],
            'RewardMoney' => ['label' => 'lang:app.quest.config.fields.form.RewardMoney.label', 'type' => 'int', 'min' => 0, 'default' => 0],
            'RewardSpell' => ['label' => 'lang:app.quest.config.fields.form.RewardSpell.label', 'type' => 'int', 'min' => 0, 'default' => 0],
            'RewardItem1' => ['label' => 'lang:app.quest.config.fields.form.RewardItem1.label', 'type' => 'int', 'min' => 0, 'default' => 0],
            'RewardAmount1' => ['label' => 'lang:app.quest.config.fields.form.RewardAmount1.label', 'type' => 'int', 'min' => 0, 'default' => 0],
            'RewardItem2' => ['label' => 'lang:app.quest.config.fields.form.RewardItem2.label', 'type' => 'int', 'min' => 0, 'default' => 0],
            'RewardAmount2' => ['label' => 'lang:app.quest.config.fields.form.RewardAmount2.label', 'type' => 'int', 'min' => 0, 'default' => 0],
            'RewardItem3' => ['label' => 'lang:app.quest.config.fields.form.RewardItem3.label', 'type' => 'int', 'min' => 0, 'default' => 0],
            'RewardAmount3' => ['label' => 'lang:app.quest.config.fields.form.RewardAmount3.label', 'type' => 'int', 'min' => 0, 'default' => 0],
            'RewardItem4' => ['label' => 'lang:app.quest.config.fields.form.RewardItem4.label', 'type' => 'int', 'min' => 0, 'default' => 0],
            'RewardAmount4' => ['label' => 'lang:app.quest.config.fields.form.RewardAmount4.label', 'type' => 'int', 'min' => 0, 'default' => 0],
            'SrcSpell' => ['label' => 'lang:app.quest.config.fields.form.SrcSpell.label', 'type' => 'int', 'min' => 0, 'default' => 0],
            'StartItem' => ['label' => 'lang:app.quest.config.fields.form.StartItem.label', 'type' => 'int', 'min' => 0, 'default' => 0],
            'RewardMailTemplateId' => ['label' => 'lang:app.quest.config.fields.form.RewardMailTemplateId.label', 'type' => 'int', 'min' => 0, 'default' => 0],
        ],
    ],
    'metadata' => [
        'template_groups' => [
            'identity' => [
                'label' => 'lang:app.quest.config.metadata.template_groups.identity.label',
                'fields' => ['ID', 'LogTitle', 'LogDescription', 'QuestDescription', 'AreaDescription', 'QuestCompletionLog'],
            ],
            'progression' => [
                'label' => 'lang:app.quest.config.metadata.template_groups.progression.label',
                'fields' => ['QuestType', 'QuestLevel', 'MinLevel', 'SuggestedGroupNum', 'QuestSortID', 'QuestInfoID', 'RewardNextQuest', 'TimeAllowed', 'RequiredPlayerKills'],
            ],
            'requirements' => [
                'label' => 'lang:app.quest.config.metadata.template_groups.requirements.label',
                'fields' => ['AllowableRaces', 'RequiredFactionId1', 'RequiredFactionValue1', 'RequiredFactionId2', 'RequiredFactionValue2'],
            ],
            'objectives' => [
                'label' => 'lang:app.quest.config.metadata.template_groups.objectives.label',
                'fields' => [
                    'ObjectiveText1',
                    'ObjectiveText2',
                    'ObjectiveText3',
                    'ObjectiveText4',
                    'RequiredNpcOrGo1',
                    'RequiredNpcOrGoCount1',
                    'RequiredNpcOrGo2',
                    'RequiredNpcOrGoCount2',
                    'RequiredNpcOrGo3',
                    'RequiredNpcOrGoCount3',
                    'RequiredNpcOrGo4',
                    'RequiredNpcOrGoCount4',
                    'RequiredItemId1',
                    'RequiredItemCount1',
                    'RequiredItemId2',
                    'RequiredItemCount2',
                    'RequiredItemId3',
                    'RequiredItemCount3',
                    'RequiredItemId4',
                    'RequiredItemCount4',
                    'RequiredItemId5',
                    'RequiredItemCount5',
                    'RequiredItemId6',
                    'RequiredItemCount6',
                ],
            ],
            'rewards' => [
                'label' => 'lang:app.quest.config.metadata.template_groups.rewards.label',
                'fields' => [
                    'RewardMoney',
                    'RewardMoneyDifficulty',
                    'RewardXPDifficulty',
                    'RewardHonor',
                    'RewardKillHonor',
                    'RewardTitle',
                    'RewardTalents',
                    'RewardArenaPoints',
                    'RewardSpell',
                    'RewardDisplaySpell',
                    'RewardItem1',
                    'RewardAmount1',
                    'RewardItem2',
                    'RewardAmount2',
                    'RewardItem3',
                    'RewardAmount3',
                    'RewardItem4',
                    'RewardAmount4',
                    'RewardChoiceItemID1',
                    'RewardChoiceItemQuantity1',
                    'RewardChoiceItemID2',
                    'RewardChoiceItemQuantity2',
                    'RewardChoiceItemID3',
                    'RewardChoiceItemQuantity3',
                    'RewardChoiceItemID4',
                    'RewardChoiceItemQuantity4',
                    'RewardChoiceItemID5',
                    'RewardChoiceItemQuantity5',
                    'RewardChoiceItemID6',
                    'RewardChoiceItemQuantity6',
                ],
            ],
            'flags' => [
                'label' => 'lang:app.quest.config.metadata.template_groups.flags.label',
                'fields' => [
                    'Flags',
                    'RewardFactionOverride1',
                    'RewardFactionOverride2',
                    'RewardFactionOverride3',
                    'RewardFactionOverride4',
                    'RewardFactionOverride5',
                    'POIContinent',
                    'POIx',
                    'POIy',
                    'POIPriority',
                    'ItemDrop1',
                    'ItemDropQuantity1',
                    'ItemDrop2',
                    'ItemDropQuantity2',
                    'ItemDrop3',
                    'ItemDropQuantity3',
                    'ItemDrop4',
                    'ItemDropQuantity4',
                    'VerifiedBuild',
                ],
            ],
        ],
        'addon_fields' => [
            'MaxLevel',
            'AllowableClasses',
            'SourceSpellID',
            'PrevQuestID',
            'NextQuestID',
            'ExclusiveGroup',
            'BreadcrumbQuestID',
            'RewardMailTemplateID',
            'RewardMailSenderEntry',
            'RewardMailDelay',
            'RequiredSkillID',
            'RequiredSkillPoints',
            'RequiredMinRepFaction',
            'RequiredMinRepValue',
            'RequiredMaxRepFaction',
            'RequiredMaxRepValue',
            'StartScript',
            'CompleteScript',
            'SpecialFlags',
            'WDBVerified',
        ],
        'narrative_tables' => [
            'details' => [
                'table' => 'quest_details',
                'label' => 'lang:app.quest.config.metadata.narrative_tables.details.label',
                'fields' => ['Emote1', 'Emote2', 'Emote3', 'Emote4', 'EmoteDelay1', 'EmoteDelay2', 'EmoteDelay3', 'EmoteDelay4', 'EmoteOnIncomplete', 'EmoteOnComplete', 'VerifiedBuild'],
            ],
            'request' => [
                'table' => 'quest_request_items',
                'label' => 'lang:app.quest.config.metadata.narrative_tables.request.label',
                'fields' => ['CompletionText', 'VerifiedBuild'],
            ],
            'offer' => [
                'table' => 'quest_offer_reward',
                'label' => 'lang:app.quest.config.metadata.narrative_tables.offer.label',
                'fields' => ['RewardText', 'VerifiedBuild', 'Emote1', 'Emote2', 'Emote3', 'Emote4', 'EmoteDelay1', 'EmoteDelay2', 'EmoteDelay3', 'EmoteDelay4'],
            ],
        ],
        'objective_schema' => [
            'table' => 'quest_objectives',
            'key' => 'ID',
            'quest_key' => 'QuestID',
            'fields' => ['Index', 'Type', 'StorageIndex', 'ObjectID', 'Amount', 'Flags', 'Description'],
        ],
        'reward_tables' => [
            'choice_items' => [
                'table' => 'quest_reward_choice_item',
                'label' => 'lang:app.quest.config.metadata.reward_tables.choice_items.label',
                'fields' => ['ItemID', 'ItemQuantity'],
            ],
            'items' => [
                'table' => 'quest_reward_item',
                'label' => 'lang:app.quest.config.metadata.reward_tables.items.label',
                'fields' => ['ItemID', 'ItemQuantity'],
            ],
            'currencies' => [
                'table' => 'quest_reward_currency',
                'label' => 'lang:app.quest.config.metadata.reward_tables.currencies.label',
                'fields' => ['CurrencyID', 'Quantity'],
            ],
            'factions' => [
                'table' => 'quest_reward_faction',
                'label' => 'lang:app.quest.config.metadata.reward_tables.factions.label',
                'fields' => ['FactionID', 'Value', 'Override'],
            ],
        ],
        'relation_sets' => [
            'starters' => [
                'creatures' => ['table' => 'creature_queststarter', 'entity_column' => 'id', 'quest_column' => 'quest'],
                'gameobjects' => ['table' => 'gameobject_queststarter', 'entity_column' => 'id', 'quest_column' => 'quest'],
            ],
            'enders' => [
                'creatures' => ['table' => 'creature_questender', 'entity_column' => 'id', 'quest_column' => 'quest'],
                'gameobjects' => ['table' => 'gameobject_questender', 'entity_column' => 'id', 'quest_column' => 'quest'],
            ],
        ],
        'locale_tables' => [
            'template' => ['table' => 'quest_template_locale', 'text_columns' => ['LogTitle', 'LogDescription', 'QuestDescription', 'QuestCompletionLog', 'AreaDescription', 'ObjectiveText1', 'ObjectiveText2', 'ObjectiveText3', 'ObjectiveText4']],
            'details' => ['table' => 'quest_details_locale', 'text_columns' => []],
            'request' => ['table' => 'quest_request_items_locale', 'text_columns' => []],
            'offer' => ['table' => 'quest_offer_reward_locale', 'text_columns' => []],
        ],
        'poi_tables' => [
            'headers' => ['table' => 'quest_poi', 'quest_column' => 'QuestID'],
            'points' => ['table' => 'quest_poi_points', 'quest_column' => 'QuestID'],
        ],
    ],
];

