<?php
/**
 * File: config/smartai_catalog.php
 * Purpose: Provides functionality for the config module.
 */

return [
    'metadata' => [
        'updated_at' => '2025-09-29',
        'source' => 'https://www.azerothcore.org/wiki/smart_scripts',
        'notes' => [
            'lang:app.smartai.catalog.metadata.notes.0',
            'lang:app.smartai.catalog.metadata.notes.1',
        ],
    ],
    'source_types' => [
        ['value' => 0, 'label' => 'lang:app.smartai.catalog.source_types.0.label'],
        ['value' => 1, 'label' => 'lang:app.smartai.catalog.source_types.1.label'],
        ['value' => 2, 'label' => 'lang:app.smartai.catalog.source_types.2.label'],
        ['value' => 3, 'label' => 'lang:app.smartai.catalog.source_types.3.label'],
        ['value' => 9, 'label' => 'lang:app.smartai.catalog.source_types.9.label'],
    ],
    'base' => [
        [
            'key' => 'entryorguid',
            'label' => 'lang:app.smartai.catalog.base.entryorguid.label',
            'type' => 'number',
            'required' => true,
            'hint' => 'lang:app.smartai.catalog.base.entryorguid.hint',
        ],
        [
            'key' => 'source_type',
            'label' => 'lang:app.smartai.catalog.base.source_type.label',
            'type' => 'select',
            'options' => 'source_types',
            'default' => 0,
            'hint' => 'lang:app.smartai.catalog.base.source_type.hint',
        ],
        [
            'key' => 'id',
            'label' => 'lang:app.smartai.catalog.base.id.label',
            'type' => 'number',
            'default' => 0,
            'hint' => 'lang:app.smartai.catalog.base.id.hint',
        ],
        [
            'key' => 'link',
            'label' => 'lang:app.smartai.catalog.base.link.label',
            'type' => 'number',
            'default' => 0,
            'hint' => 'lang:app.smartai.catalog.base.link.hint',
        ],
        [
            'key' => 'event_phase_mask',
            'label' => 'lang:app.smartai.catalog.base.event_phase_mask.label',
            'type' => 'number',
            'default' => 0,
            'hint' => 'lang:app.smartai.catalog.base.event_phase_mask.hint',
        ],
        [
            'key' => 'event_chance',
            'label' => 'lang:app.smartai.catalog.base.event_chance.label',
            'type' => 'number',
            'default' => 100,
            'hint' => 'lang:app.smartai.catalog.base.event_chance.hint',
        ],
        [
            'key' => 'event_flags',
            'label' => 'lang:app.smartai.catalog.base.event_flags.label',
            'type' => 'number',
            'default' => 0,
            'hint' => 'lang:app.smartai.catalog.base.event_flags.hint',
        ],
        [
            'key' => 'comment',
            'label' => 'lang:app.smartai.catalog.base.comment.label',
            'type' => 'text',
            'default' => '',
            'hint' => 'lang:app.smartai.catalog.base.comment.hint',
        ],
        [
            'key' => 'include_delete',
            'label' => 'lang:app.smartai.catalog.base.include_delete.label',
            'type' => 'checkbox',
            'default' => true,
            'hint' => 'lang:app.smartai.catalog.base.include_delete.hint',
        ],
    ],
    'events' => [
        [
            'id' => 0,
            'code' => 'SMART_EVENT_UPDATE_IC',
            'name' => 'lang:app.smartai.catalog.events.0.name',
            'category' => 'lang:app.smartai.catalog.events.0.category',
            'description' => 'lang:app.smartai.catalog.events.0.description',
            'params' => [
                ['column' => 'event_param1', 'label' => 'lang:app.smartai.catalog.events.0.params.event_param1.label', 'type' => 'number', 'default' => 1000, 'hint' => 'lang:app.smartai.catalog.events.0.params.event_param1.hint'],
                ['column' => 'event_param2', 'label' => 'lang:app.smartai.catalog.events.0.params.event_param2.label', 'type' => 'number', 'default' => 1000, 'hint' => 'lang:app.smartai.catalog.events.0.params.event_param2.hint'],
                ['column' => 'event_param3', 'label' => 'lang:app.smartai.catalog.events.0.params.event_param3.label', 'type' => 'number', 'default' => 5000, 'hint' => 'lang:app.smartai.catalog.events.0.params.event_param3.hint'],
                ['column' => 'event_param4', 'label' => 'lang:app.smartai.catalog.events.0.params.event_param4.label', 'type' => 'number', 'default' => 7000, 'hint' => 'lang:app.smartai.catalog.events.0.params.event_param4.hint'],
            ],
        ],
        [
            'id' => 1,
            'code' => 'SMART_EVENT_UPDATE_OOC',
            'name' => 'lang:app.smartai.catalog.events.1.name',
            'category' => 'lang:app.smartai.catalog.events.1.category',
            'description' => 'lang:app.smartai.catalog.events.1.description',
            'params' => [
                ['column' => 'event_param1', 'label' => 'lang:app.smartai.catalog.events.1.params.event_param1.label', 'type' => 'number', 'default' => 1000, 'hint' => 'lang:app.smartai.catalog.events.1.params.event_param1.hint'],
                ['column' => 'event_param2', 'label' => 'lang:app.smartai.catalog.events.1.params.event_param2.label', 'type' => 'number', 'default' => 1000, 'hint' => 'lang:app.smartai.catalog.events.1.params.event_param2.hint'],
                ['column' => 'event_param3', 'label' => 'lang:app.smartai.catalog.events.1.params.event_param3.label', 'type' => 'number', 'default' => 5000, 'hint' => 'lang:app.smartai.catalog.events.1.params.event_param3.hint'],
                ['column' => 'event_param4', 'label' => 'lang:app.smartai.catalog.events.1.params.event_param4.label', 'type' => 'number', 'default' => 7000, 'hint' => 'lang:app.smartai.catalog.events.1.params.event_param4.hint'],
            ],
        ],
        [
            'id' => 2,
            'code' => 'SMART_EVENT_HEALTH_PCT',
            'name' => 'lang:app.smartai.catalog.events.2.name',
            'category' => 'lang:app.smartai.catalog.events.2.category',
            'description' => 'lang:app.smartai.catalog.events.2.description',
            'params' => [
                ['column' => 'event_param1', 'label' => 'lang:app.smartai.catalog.events.2.params.event_param1.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.2.params.event_param1.hint'],
                ['column' => 'event_param2', 'label' => 'lang:app.smartai.catalog.events.2.params.event_param2.label', 'type' => 'number', 'default' => 30, 'hint' => 'lang:app.smartai.catalog.events.2.params.event_param2.hint'],
                ['column' => 'event_param3', 'label' => 'lang:app.smartai.catalog.events.2.params.event_param3.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.2.params.event_param3.hint'],
                ['column' => 'event_param4', 'label' => 'lang:app.smartai.catalog.events.2.params.event_param4.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.2.params.event_param4.hint'],
            ],
        ],
        [
            'id' => 3,
            'code' => 'SMART_EVENT_MANA_PCT',
            'name' => 'lang:app.smartai.catalog.events.3.name',
            'category' => 'lang:app.smartai.catalog.events.3.category',
            'description' => 'lang:app.smartai.catalog.events.3.description',
            'params' => [
                ['column' => 'event_param1', 'label' => 'lang:app.smartai.catalog.events.3.params.event_param1.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.3.params.event_param1.hint'],
                ['column' => 'event_param2', 'label' => 'lang:app.smartai.catalog.events.3.params.event_param2.label', 'type' => 'number', 'default' => 30, 'hint' => 'lang:app.smartai.catalog.events.3.params.event_param2.hint'],
                ['column' => 'event_param3', 'label' => 'lang:app.smartai.catalog.events.3.params.event_param3.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.3.params.event_param3.hint'],
                ['column' => 'event_param4', 'label' => 'lang:app.smartai.catalog.events.3.params.event_param4.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.3.params.event_param4.hint'],
            ],
        ],
        [
            'id' => 4,
            'code' => 'SMART_EVENT_AGGRO',
            'name' => 'lang:app.smartai.catalog.events.4.name',
            'category' => 'lang:app.smartai.catalog.events.4.category',
            'description' => 'lang:app.smartai.catalog.events.4.description',
            'params' => [
                ['column' => 'event_param1', 'label' => 'lang:app.smartai.catalog.events.4.params.event_param1.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.4.params.event_param1.hint'],
                ['column' => 'event_param2', 'label' => 'lang:app.smartai.catalog.events.4.params.event_param2.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.4.params.event_param2.hint'],
                ['column' => 'event_param3', 'label' => 'lang:app.smartai.catalog.events.4.params.event_param3.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.4.params.event_param3.hint'],
                ['column' => 'event_param4', 'label' => 'lang:app.smartai.catalog.events.4.params.event_param4.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.4.params.event_param4.hint'],
            ],
        ],
        [
            'id' => 8,
            'code' => 'SMART_EVENT_SPELLHIT',
            'name' => 'lang:app.smartai.catalog.events.8.name',
            'category' => 'lang:app.smartai.catalog.events.8.category',
            'description' => 'lang:app.smartai.catalog.events.8.description',
            'params' => [
                ['column' => 'event_param1', 'label' => 'lang:app.smartai.catalog.events.8.params.event_param1.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.8.params.event_param1.hint'],
                ['column' => 'event_param2', 'label' => 'lang:app.smartai.catalog.events.8.params.event_param2.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.8.params.event_param2.hint'],
                ['column' => 'event_param3', 'label' => 'lang:app.smartai.catalog.events.8.params.event_param3.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.8.params.event_param3.hint'],
                ['column' => 'event_param4', 'label' => 'lang:app.smartai.catalog.events.8.params.event_param4.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.8.params.event_param4.hint'],
            ],
        ],
        [
            'id' => 9,
            'code' => 'SMART_EVENT_RANGE',
            'name' => 'lang:app.smartai.catalog.events.9.name',
            'category' => 'lang:app.smartai.catalog.events.9.category',
            'description' => 'lang:app.smartai.catalog.events.9.description',
            'params' => [
                ['column' => 'event_param1', 'label' => 'lang:app.smartai.catalog.events.9.params.event_param1.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.9.params.event_param1.hint'],
                ['column' => 'event_param2', 'label' => 'lang:app.smartai.catalog.events.9.params.event_param2.label', 'type' => 'number', 'default' => 5, 'hint' => 'lang:app.smartai.catalog.events.9.params.event_param2.hint'],
                ['column' => 'event_param3', 'label' => 'lang:app.smartai.catalog.events.9.params.event_param3.label', 'type' => 'number', 'default' => 2000, 'hint' => 'lang:app.smartai.catalog.events.9.params.event_param3.hint'],
                ['column' => 'event_param4', 'label' => 'lang:app.smartai.catalog.events.9.params.event_param4.label', 'type' => 'number', 'default' => 4000, 'hint' => 'lang:app.smartai.catalog.events.9.params.event_param4.hint'],
            ],
        ],
        [
            'id' => 10,
            'code' => 'SMART_EVENT_OOC_LOS',
            'name' => 'lang:app.smartai.catalog.events.10.name',
            'category' => 'lang:app.smartai.catalog.events.10.category',
            'description' => 'lang:app.smartai.catalog.events.10.description',
            'params' => [
                ['column' => 'event_param1', 'label' => 'lang:app.smartai.catalog.events.10.params.event_param1.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.10.params.event_param1.hint'],
                ['column' => 'event_param2', 'label' => 'lang:app.smartai.catalog.events.10.params.event_param2.label', 'type' => 'number', 'default' => 20, 'hint' => 'lang:app.smartai.catalog.events.10.params.event_param2.hint'],
                ['column' => 'event_param3', 'label' => 'lang:app.smartai.catalog.events.10.params.event_param3.label', 'type' => 'number', 'default' => 5000, 'hint' => 'lang:app.smartai.catalog.events.10.params.event_param3.hint'],
                ['column' => 'event_param4', 'label' => 'lang:app.smartai.catalog.events.10.params.event_param4.label', 'type' => 'number', 'default' => 10000, 'hint' => 'lang:app.smartai.catalog.events.10.params.event_param4.hint'],
            ],
        ],
        [
            'id' => 16,
            'code' => 'SMART_EVENT_TIMER',
            'name' => 'lang:app.smartai.catalog.events.16.name',
            'category' => 'lang:app.smartai.catalog.events.16.category',
            'description' => 'lang:app.smartai.catalog.events.16.description',
            'params' => [
                ['column' => 'event_param1', 'label' => 'lang:app.smartai.catalog.events.16.params.event_param1.label', 'type' => 'number', 'default' => 1000, 'hint' => 'lang:app.smartai.catalog.events.16.params.event_param1.hint'],
                ['column' => 'event_param2', 'label' => 'lang:app.smartai.catalog.events.16.params.event_param2.label', 'type' => 'number', 'default' => 2000, 'hint' => 'lang:app.smartai.catalog.events.16.params.event_param2.hint'],
                ['column' => 'event_param3', 'label' => 'lang:app.smartai.catalog.events.16.params.event_param3.label', 'type' => 'number', 'default' => 5000, 'hint' => 'lang:app.smartai.catalog.events.16.params.event_param3.hint'],
                ['column' => 'event_param4', 'label' => 'lang:app.smartai.catalog.events.16.params.event_param4.label', 'type' => 'number', 'default' => 8000, 'hint' => 'lang:app.smartai.catalog.events.16.params.event_param4.hint'],
            ],
        ],
        [
            'id' => 28,
            'code' => 'SMART_EVENT_KILL',
            'name' => 'lang:app.smartai.catalog.events.28.name',
            'category' => 'lang:app.smartai.catalog.events.28.category',
            'description' => 'lang:app.smartai.catalog.events.28.description',
            'params' => [
                ['column' => 'event_param1', 'label' => 'lang:app.smartai.catalog.events.28.params.event_param1.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.28.params.event_param1.hint'],
                ['column' => 'event_param2', 'label' => 'lang:app.smartai.catalog.events.28.params.event_param2.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.28.params.event_param2.hint'],
                ['column' => 'event_param3', 'label' => 'lang:app.smartai.catalog.events.28.params.event_param3.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.28.params.event_param3.hint'],
                ['column' => 'event_param4', 'label' => 'lang:app.smartai.catalog.events.28.params.event_param4.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.events.28.params.event_param4.hint'],
            ],
        ],
    ],
    'actions' => [
        [
            'id' => 0,
            'code' => 'SMART_ACTION_NONE',
            'name' => 'lang:app.smartai.catalog.actions.0.name',
            'category' => 'lang:app.smartai.catalog.actions.0.category',
            'description' => 'lang:app.smartai.catalog.actions.0.description',
            'params' => [],
        ],
        [
            'id' => 1,
            'code' => 'SMART_ACTION_TALK',
            'name' => 'lang:app.smartai.catalog.actions.1.name',
            'category' => 'lang:app.smartai.catalog.actions.1.category',
            'description' => 'lang:app.smartai.catalog.actions.1.description',
            'params' => [
                ['column' => 'action_param1', 'label' => 'lang:app.smartai.catalog.actions.1.params.action_param1.label', 'type' => 'number', 'default' => 0, 'required' => true, 'hint' => 'lang:app.smartai.catalog.actions.1.params.action_param1.hint'],
                ['column' => 'action_param2', 'label' => 'lang:app.smartai.catalog.actions.1.params.action_param2.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.1.params.action_param2.hint'],
                ['column' => 'action_param3', 'label' => 'lang:app.smartai.catalog.actions.1.params.action_param3.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.1.params.action_param3.hint'],
                ['column' => 'action_param4', 'label' => 'lang:app.smartai.catalog.actions.1.params.action_param4.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.1.params.action_param4.hint'],
                ['column' => 'action_param5', 'label' => 'lang:app.smartai.catalog.actions.1.params.action_param5.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.1.params.action_param5.hint'],
                ['column' => 'action_param6', 'label' => 'lang:app.smartai.catalog.actions.1.params.action_param6.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.1.params.action_param6.hint'],
            ],
        ],
        [
            'id' => 2,
            'code' => 'SMART_ACTION_SET_FACTION',
            'name' => 'lang:app.smartai.catalog.actions.2.name',
            'category' => 'lang:app.smartai.catalog.actions.2.category',
            'description' => 'lang:app.smartai.catalog.actions.2.description',
            'params' => [
                ['column' => 'action_param1', 'label' => 'lang:app.smartai.catalog.actions.2.params.action_param1.label', 'type' => 'number', 'default' => 0, 'required' => true, 'hint' => 'lang:app.smartai.catalog.actions.2.params.action_param1.hint'],
            ],
        ],
        [
            'id' => 3,
            'code' => 'SMART_ACTION_MORPH_TO_ENTRY_OR_MODEL',
            'name' => 'lang:app.smartai.catalog.actions.3.name',
            'category' => 'lang:app.smartai.catalog.actions.3.category',
            'description' => 'lang:app.smartai.catalog.actions.3.description',
            'params' => [
                ['column' => 'action_param1', 'label' => 'lang:app.smartai.catalog.actions.3.params.action_param1.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.3.params.action_param1.hint'],
                ['column' => 'action_param2', 'label' => 'lang:app.smartai.catalog.actions.3.params.action_param2.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.3.params.action_param2.hint'],
            ],
        ],
        [
            'id' => 4,
            'code' => 'SMART_ACTION_SOUND',
            'name' => 'lang:app.smartai.catalog.actions.4.name',
            'category' => 'lang:app.smartai.catalog.actions.4.category',
            'description' => 'lang:app.smartai.catalog.actions.4.description',
            'params' => [
                ['column' => 'action_param1', 'label' => 'lang:app.smartai.catalog.actions.4.params.action_param1.label', 'type' => 'number', 'default' => 0, 'required' => true, 'hint' => 'lang:app.smartai.catalog.actions.4.params.action_param1.hint'],
                ['column' => 'action_param2', 'label' => 'lang:app.smartai.catalog.actions.4.params.action_param2.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.4.params.action_param2.hint'],
                ['column' => 'action_param3', 'label' => 'lang:app.smartai.catalog.actions.4.params.action_param3.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.4.params.action_param3.hint'],
            ],
        ],
        [
            'id' => 5,
            'code' => 'SMART_ACTION_PLAY_EMOTE',
            'name' => 'lang:app.smartai.catalog.actions.5.name',
            'category' => 'lang:app.smartai.catalog.actions.5.category',
            'description' => 'lang:app.smartai.catalog.actions.5.description',
            'params' => [
                ['column' => 'action_param1', 'label' => 'lang:app.smartai.catalog.actions.5.params.action_param1.label', 'type' => 'number', 'default' => 1, 'required' => true, 'hint' => 'lang:app.smartai.catalog.actions.5.params.action_param1.hint'],
            ],
        ],
        [
            'id' => 11,
            'code' => 'SMART_ACTION_CAST',
            'name' => 'lang:app.smartai.catalog.actions.11.name',
            'category' => 'lang:app.smartai.catalog.actions.11.category',
            'description' => 'lang:app.smartai.catalog.actions.11.description',
            'params' => [
                ['column' => 'action_param1', 'label' => 'lang:app.smartai.catalog.actions.11.params.action_param1.label', 'type' => 'number', 'default' => 0, 'required' => true, 'hint' => 'lang:app.smartai.catalog.actions.11.params.action_param1.hint'],
                ['column' => 'action_param2', 'label' => 'lang:app.smartai.catalog.actions.11.params.action_param2.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.11.params.action_param2.hint'],
                ['column' => 'action_param3', 'label' => 'lang:app.smartai.catalog.actions.11.params.action_param3.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.11.params.action_param3.hint'],
                ['column' => 'action_param4', 'label' => 'lang:app.smartai.catalog.actions.11.params.action_param4.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.11.params.action_param4.hint'],
                ['column' => 'action_param5', 'label' => 'lang:app.smartai.catalog.actions.11.params.action_param5.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.11.params.action_param5.hint'],
                ['column' => 'action_param6', 'label' => 'lang:app.smartai.catalog.actions.11.params.action_param6.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.11.params.action_param6.hint'],
            ],
        ],
        [
            'id' => 12,
            'code' => 'SMART_ACTION_SUMMON_CREATURE',
            'name' => 'lang:app.smartai.catalog.actions.12.name',
            'category' => 'lang:app.smartai.catalog.actions.12.category',
            'description' => 'lang:app.smartai.catalog.actions.12.description',
            'params' => [
                ['column' => 'action_param1', 'label' => 'lang:app.smartai.catalog.actions.12.params.action_param1.label', 'type' => 'number', 'default' => 0, 'required' => true, 'hint' => 'lang:app.smartai.catalog.actions.12.params.action_param1.hint'],
                ['column' => 'action_param2', 'label' => 'lang:app.smartai.catalog.actions.12.params.action_param2.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.12.params.action_param2.hint'],
                ['column' => 'action_param3', 'label' => 'lang:app.smartai.catalog.actions.12.params.action_param3.label', 'type' => 'number', 'default' => 1, 'hint' => 'lang:app.smartai.catalog.actions.12.params.action_param3.hint'],
                ['column' => 'action_param4', 'label' => 'lang:app.smartai.catalog.actions.12.params.action_param4.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.12.params.action_param4.hint'],
                ['column' => 'action_param5', 'label' => 'lang:app.smartai.catalog.actions.12.params.action_param5.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.12.params.action_param5.hint'],
                ['column' => 'action_param6', 'label' => 'lang:app.smartai.catalog.actions.12.params.action_param6.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.12.params.action_param6.hint'],
            ],
        ],
        [
            'id' => 21,
            'code' => 'SMART_ACTION_AUTO_ATTACK',
            'name' => 'lang:app.smartai.catalog.actions.21.name',
            'category' => 'lang:app.smartai.catalog.actions.21.category',
            'description' => 'lang:app.smartai.catalog.actions.21.description',
            'params' => [
                ['column' => 'action_param1', 'label' => 'lang:app.smartai.catalog.actions.21.params.action_param1.label', 'type' => 'number', 'default' => 1, 'hint' => 'lang:app.smartai.catalog.actions.21.params.action_param1.hint'],
            ],
        ],
        [
            'id' => 28,
            'code' => 'SMART_ACTION_ADD_AURA',
            'name' => 'lang:app.smartai.catalog.actions.28.name',
            'category' => 'lang:app.smartai.catalog.actions.28.category',
            'description' => 'lang:app.smartai.catalog.actions.28.description',
            'params' => [
                ['column' => 'action_param1', 'label' => 'lang:app.smartai.catalog.actions.28.params.action_param1.label', 'type' => 'number', 'default' => 0, 'required' => true, 'hint' => 'lang:app.smartai.catalog.actions.28.params.action_param1.hint'],
                ['column' => 'action_param2', 'label' => 'lang:app.smartai.catalog.actions.28.params.action_param2.label', 'type' => 'number', 'default' => 1, 'hint' => 'lang:app.smartai.catalog.actions.28.params.action_param2.hint'],
                ['column' => 'action_param3', 'label' => 'lang:app.smartai.catalog.actions.28.params.action_param3.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.actions.28.params.action_param3.hint'],
            ],
        ],
    ],
    'targets' => [
        [
            'id' => 0,
            'code' => 'SMART_TARGET_NONE',
            'name' => 'lang:app.smartai.catalog.targets.0.name',
            'category' => 'lang:app.smartai.catalog.targets.0.category',
            'description' => 'lang:app.smartai.catalog.targets.0.description',
            'params' => [],
        ],
        [
            'id' => 1,
            'code' => 'SMART_TARGET_SELF',
            'name' => 'lang:app.smartai.catalog.targets.1.name',
            'category' => 'lang:app.smartai.catalog.targets.1.category',
            'description' => 'lang:app.smartai.catalog.targets.1.description',
            'params' => [],
        ],
        [
            'id' => 2,
            'code' => 'SMART_TARGET_VICTIM',
            'name' => 'lang:app.smartai.catalog.targets.2.name',
            'category' => 'lang:app.smartai.catalog.targets.2.category',
            'description' => 'lang:app.smartai.catalog.targets.2.description',
            'params' => [],
        ],
        [
            'id' => 4,
            'code' => 'SMART_TARGET_HOSTILE_LAST_AGGRO',
            'name' => 'lang:app.smartai.catalog.targets.4.name',
            'category' => 'lang:app.smartai.catalog.targets.4.category',
            'description' => 'lang:app.smartai.catalog.targets.4.description',
            'params' => [],
        ],
        [
            'id' => 5,
            'code' => 'SMART_TARGET_HOSTILE_RANDOM',
            'name' => 'lang:app.smartai.catalog.targets.5.name',
            'category' => 'lang:app.smartai.catalog.targets.5.category',
            'description' => 'lang:app.smartai.catalog.targets.5.description',
            'params' => [
                ['column' => 'target_param1', 'label' => 'lang:app.smartai.catalog.targets.5.params.target_param1.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.targets.5.params.target_param1.hint'],
                ['column' => 'target_param2', 'label' => 'lang:app.smartai.catalog.targets.5.params.target_param2.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.targets.5.params.target_param2.hint'],
                ['column' => 'target_param3', 'label' => 'lang:app.smartai.catalog.targets.5.params.target_param3.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.targets.5.params.target_param3.hint'],
            ],
        ],
        [
            'id' => 7,
            'code' => 'SMART_TARGET_ACTION_INVOKER',
            'name' => 'lang:app.smartai.catalog.targets.7.name',
            'category' => 'lang:app.smartai.catalog.targets.7.category',
            'description' => 'lang:app.smartai.catalog.targets.7.description',
            'params' => [],
        ],
        [
            'id' => 8,
            'code' => 'SMART_TARGET_POSITION',
            'name' => 'lang:app.smartai.catalog.targets.8.name',
            'category' => 'lang:app.smartai.catalog.targets.8.category',
            'description' => 'lang:app.smartai.catalog.targets.8.description',
            'params' => [
                ['column' => 'target_x', 'label' => 'lang:app.smartai.catalog.targets.8.params.target_x.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.targets.8.params.target_x.hint'],
                ['column' => 'target_y', 'label' => 'lang:app.smartai.catalog.targets.8.params.target_y.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.targets.8.params.target_y.hint'],
                ['column' => 'target_z', 'label' => 'lang:app.smartai.catalog.targets.8.params.target_z.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.targets.8.params.target_z.hint'],
                ['column' => 'target_o', 'label' => 'lang:app.smartai.catalog.targets.8.params.target_o.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.targets.8.params.target_o.hint'],
            ],
        ],
        [
            'id' => 9,
            'code' => 'SMART_TARGET_POSITION_AND_SUMMONER',
            'name' => 'lang:app.smartai.catalog.targets.9.name',
            'category' => 'lang:app.smartai.catalog.targets.9.category',
            'description' => 'lang:app.smartai.catalog.targets.9.description',
            'params' => [
                ['column' => 'target_param1', 'label' => 'lang:app.smartai.catalog.targets.9.params.target_param1.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.targets.9.params.target_param1.hint'],
                ['column' => 'target_param2', 'label' => 'lang:app.smartai.catalog.targets.9.params.target_param2.label', 'type' => 'number', 'default' => 0, 'hint' => 'lang:app.smartai.catalog.targets.9.params.target_param2.hint'],
            ],
        ],
    ],
];

